baseURL = 'https://adrian-1bos.github.io/Catalogo/'
canonifyURLs = true
locale = 'pt-br'
title = 'Catálogo Artesanal'
theme = 'papermod'

[params]
  homeInfoParams = {Title = "Nossos Produtos Artesanais", Content = "Feito à mão."}

[menu]
  [[menu.main]]
    name = "Produtos"
    url = "/"
    weight = 1

[outputs]
  home = ["HTML"]

[outputFormats.RSS]
  path = "feed/index.xml"